[features]
seeds = false
skip-lint = false

[programs.mainnet]
unatrare_salute_burn = "2kociKNJcSLo1TytiyWvT1r8sdFdLMZu9mMYHfogjxZc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
